from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DORM_ROSTER_CHECK = Button(area={'cn': (200, 96, 312, 126), 'en': (200, 96, 312, 126), 'jp': (200, 96, 312, 126), 'tw': (200, 96, 312, 126)}, color={'cn': (199, 199, 200), 'en': (199, 199, 200), 'jp': (199, 199, 200), 'tw': (199, 199, 200)}, button={'cn': (200, 96, 312, 126), 'en': (200, 96, 312, 126), 'jp': (200, 96, 312, 126), 'tw': (200, 96, 312, 126)}, file={'cn': './assets/cn/ship_leveling/DORM_ROSTER_CHECK.png', 'en': './assets/en/ship_leveling/DORM_ROSTER_CHECK.png', 'jp': './assets/cn/ship_leveling/DORM_ROSTER_CHECK.png', 'tw': './assets/cn/ship_leveling/DORM_ROSTER_CHECK.png'})
