from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

TEMPLATE_ENH_FILL = Template(file={'cn': './assets/cn/ship_census/TEMPLATE_ENH_FILL.png', 'en': './assets/en/ship_census/TEMPLATE_ENH_FILL.png', 'jp': './assets/cn/ship_census/TEMPLATE_ENH_FILL.png', 'tw': './assets/cn/ship_census/TEMPLATE_ENH_FILL.png'})
TEMPLATE_ENH_MAX = Template(file={'cn': './assets/cn/ship_census/TEMPLATE_ENH_MAX.png', 'en': './assets/en/ship_census/TEMPLATE_ENH_MAX.png', 'jp': './assets/cn/ship_census/TEMPLATE_ENH_MAX.png', 'tw': './assets/cn/ship_census/TEMPLATE_ENH_MAX.png'})
TEMPLATE_SKILL_LOCKED = Template(file={'cn': './assets/cn/ship_census/TEMPLATE_SKILL_LOCKED.png', 'en': './assets/en/ship_census/TEMPLATE_SKILL_LOCKED.png', 'jp': './assets/cn/ship_census/TEMPLATE_SKILL_LOCKED.png', 'tw': './assets/cn/ship_census/TEMPLATE_SKILL_LOCKED.png'})
TEMPLATE_SKILL_UNKNOWN = Template(file={'cn': './assets/cn/ship_census/TEMPLATE_SKILL_UNKNOWN.png', 'en': './assets/en/ship_census/TEMPLATE_SKILL_UNKNOWN.png', 'jp': './assets/cn/ship_census/TEMPLATE_SKILL_UNKNOWN.png', 'tw': './assets/cn/ship_census/TEMPLATE_SKILL_UNKNOWN.png'})
TEMPLATE_STAR_EMPTY = Template(file={'cn': './assets/cn/ship_census/TEMPLATE_STAR_EMPTY.png', 'en': './assets/en/ship_census/TEMPLATE_STAR_EMPTY.png', 'jp': './assets/cn/ship_census/TEMPLATE_STAR_EMPTY.png', 'tw': './assets/cn/ship_census/TEMPLATE_STAR_EMPTY.png'})
TEMPLATE_STAR_GOLD = Template(file={'cn': './assets/cn/ship_census/TEMPLATE_STAR_GOLD.png', 'en': './assets/en/ship_census/TEMPLATE_STAR_GOLD.png', 'jp': './assets/cn/ship_census/TEMPLATE_STAR_GOLD.png', 'tw': './assets/cn/ship_census/TEMPLATE_STAR_GOLD.png'})
TEMPLATE_TAB_ENHANCE = Template(file={'cn': './assets/cn/ship_census/TEMPLATE_TAB_ENHANCE.png', 'en': './assets/en/ship_census/TEMPLATE_TAB_ENHANCE.png', 'jp': './assets/cn/ship_census/TEMPLATE_TAB_ENHANCE.png', 'tw': './assets/cn/ship_census/TEMPLATE_TAB_ENHANCE.png'})
TEMPLATE_TAB_INFO = Template(file={'cn': './assets/cn/ship_census/TEMPLATE_TAB_INFO.png', 'en': './assets/en/ship_census/TEMPLATE_TAB_INFO.png', 'jp': './assets/cn/ship_census/TEMPLATE_TAB_INFO.png', 'tw': './assets/cn/ship_census/TEMPLATE_TAB_INFO.png'})
TEMPLATE_TAB_RESEARCH = Template(file={'cn': './assets/cn/ship_census/TEMPLATE_TAB_RESEARCH.png', 'en': './assets/en/ship_census/TEMPLATE_TAB_RESEARCH.png', 'jp': './assets/cn/ship_census/TEMPLATE_TAB_RESEARCH.png', 'tw': './assets/cn/ship_census/TEMPLATE_TAB_RESEARCH.png'})
TEMPLATE_TIER_OATH = Template(file={'cn': './assets/cn/ship_census/TEMPLATE_TIER_OATH.png', 'en': './assets/en/ship_census/TEMPLATE_TIER_OATH.png', 'jp': './assets/cn/ship_census/TEMPLATE_TIER_OATH.png', 'tw': './assets/cn/ship_census/TEMPLATE_TIER_OATH.png'})
